language: cpp

sudo: false

matrix:
  include:

    - os: osx
      compiler: clang
      env:
        - COMPILER=clang++
      before_install:
        - brew update
        - brew install python3

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
      before_script:
        - export CXX=$COMPILER
        - make build-coverage
      after_success:
        - make mvcov
        - bash <(curl -s https://codecov.io/bash)

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libc6-dbg
      env:
        - COMPILER=clang++-3.6


before_script:
  - export CXX=$COMPILER
  - $CXX -v
  - python3 --version

script:
  - make
  - make short-tests
  - make test
