language: cpp

sudo: false

matrix:
  include:

    - os: osx
      compiler: clang
      env:
        - COMPILER=clang++
        - NONREG=true
      before_install:
        - brew update
        - brew install python3
        - pip3 install progressbar2

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - python3
            - python3-pip
      env:
        - COMPILER=g++-5
        - NONREG=false
      before_script:
        - export CXX=$COMPILER
        - make build-coverage
      after_success:
        - make mvcov
        - bash <(curl -s https://codecov.io/bash)

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - g++-5
            - python3
            - python3-pip
      env:
        - COMPILER=clang++-3.6
        - NONREG=true

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install progressbar2 --user `whoami`

before_script:
  - export CXX=$COMPILER
  - $CXX -v
  - python3 --version

script:
  - make
  - make short-tests
  - travis_wait 25 make test
  # - if [ "$NONREG" = "true" ]; then make nonreg; fi
