language: cpp

sudo: false

matrix:
  include:

    - os: osx
      compiler: clang
      env:
        - COMPILER=clang++
        - PYTHON=python
      python: "3.4"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
        - PYTHON=python
      before_script:
        - export CXX=$COMPILER
        - make build-coverage
      after_success:
        - make mvcov
        - bash <(curl -s https://codecov.io/bash)

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - COMPILER=clang++-3.6
        - PYTHON=python


before_script:
  - export CXX=$COMPILER
  - $CXX -v
  - $PYTHON --version

script:
  - make && make test
