# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pveber/w/diffsel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pveber/w/diffsel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pveber/w/diffsel/CMakeFiles /home/pveber/w/diffsel/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pveber/w/diffsel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named diffsel_lib

# Build rule for target.
diffsel_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 diffsel_lib
.PHONY : diffsel_lib

# fast build rule for target.
diffsel_lib/fast:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/build
.PHONY : diffsel_lib/fast

#=============================================================================
# Target rules for targets named multigenesingleomega

# Build rule for target.
multigenesingleomega: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multigenesingleomega
.PHONY : multigenesingleomega

# fast build rule for target.
multigenesingleomega/fast:
	$(MAKE) -f CMakeFiles/multigenesingleomega.dir/build.make CMakeFiles/multigenesingleomega.dir/build
.PHONY : multigenesingleomega/fast

#=============================================================================
# Target rules for targets named diffselsparse

# Build rule for target.
diffselsparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 diffselsparse
.PHONY : diffselsparse

# fast build rule for target.
diffselsparse/fast:
	$(MAKE) -f CMakeFiles/diffselsparse.dir/build.make CMakeFiles/diffselsparse.dir/build
.PHONY : diffselsparse/fast

#=============================================================================
# Target rules for targets named readdiffsel

# Build rule for target.
readdiffsel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 readdiffsel
.PHONY : readdiffsel

# fast build rule for target.
readdiffsel/fast:
	$(MAKE) -f CMakeFiles/readdiffsel.dir/build.make CMakeFiles/readdiffsel.dir/build
.PHONY : readdiffsel/fast

#=============================================================================
# Target rules for targets named tracecomp

# Build rule for target.
tracecomp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tracecomp
.PHONY : tracecomp

# fast build rule for target.
tracecomp/fast:
	$(MAKE) -f CMakeFiles/tracecomp.dir/build.make CMakeFiles/tracecomp.dir/build
.PHONY : tracecomp/fast

#=============================================================================
# Target rules for targets named singleomega

# Build rule for target.
singleomega: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 singleomega
.PHONY : singleomega

# fast build rule for target.
singleomega/fast:
	$(MAKE) -f CMakeFiles/singleomega.dir/build.make CMakeFiles/singleomega.dir/build
.PHONY : singleomega/fast

#=============================================================================
# Target rules for targets named diffsel

# Build rule for target.
diffsel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 diffsel
.PHONY : diffsel

# fast build rule for target.
diffsel/fast:
	$(MAKE) -f CMakeFiles/diffsel.dir/build.make CMakeFiles/diffsel.dir/build
.PHONY : diffsel/fast

src/BiologicalSequences.o: src/BiologicalSequences.cpp.o

.PHONY : src/BiologicalSequences.o

# target to build an object file
src/BiologicalSequences.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/BiologicalSequences.cpp.o
.PHONY : src/BiologicalSequences.cpp.o

src/BiologicalSequences.i: src/BiologicalSequences.cpp.i

.PHONY : src/BiologicalSequences.i

# target to preprocess a source file
src/BiologicalSequences.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/BiologicalSequences.cpp.i
.PHONY : src/BiologicalSequences.cpp.i

src/BiologicalSequences.s: src/BiologicalSequences.cpp.s

.PHONY : src/BiologicalSequences.s

# target to generate assembly for a file
src/BiologicalSequences.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/BiologicalSequences.cpp.s
.PHONY : src/BiologicalSequences.cpp.s

src/BranchSitePath.o: src/BranchSitePath.cpp.o

.PHONY : src/BranchSitePath.o

# target to build an object file
src/BranchSitePath.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/BranchSitePath.cpp.o
.PHONY : src/BranchSitePath.cpp.o

src/BranchSitePath.i: src/BranchSitePath.cpp.i

.PHONY : src/BranchSitePath.i

# target to preprocess a source file
src/BranchSitePath.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/BranchSitePath.cpp.i
.PHONY : src/BranchSitePath.cpp.i

src/BranchSitePath.s: src/BranchSitePath.cpp.s

.PHONY : src/BranchSitePath.s

# target to generate assembly for a file
src/BranchSitePath.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/BranchSitePath.cpp.s
.PHONY : src/BranchSitePath.cpp.s

src/Chain.o: src/Chain.cpp.o

.PHONY : src/Chain.o

# target to build an object file
src/Chain.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Chain.cpp.o
.PHONY : src/Chain.cpp.o

src/Chain.i: src/Chain.cpp.i

.PHONY : src/Chain.i

# target to preprocess a source file
src/Chain.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Chain.cpp.i
.PHONY : src/Chain.cpp.i

src/Chain.s: src/Chain.cpp.s

.PHONY : src/Chain.s

# target to generate assembly for a file
src/Chain.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Chain.cpp.s
.PHONY : src/Chain.cpp.s

src/Chrono.o: src/Chrono.cpp.o

.PHONY : src/Chrono.o

# target to build an object file
src/Chrono.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Chrono.cpp.o
.PHONY : src/Chrono.cpp.o

src/Chrono.i: src/Chrono.cpp.i

.PHONY : src/Chrono.i

# target to preprocess a source file
src/Chrono.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Chrono.cpp.i
.PHONY : src/Chrono.cpp.i

src/Chrono.s: src/Chrono.cpp.s

.PHONY : src/Chrono.s

# target to generate assembly for a file
src/Chrono.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Chrono.cpp.s
.PHONY : src/Chrono.cpp.s

src/CodonSequenceAlignment.o: src/CodonSequenceAlignment.cpp.o

.PHONY : src/CodonSequenceAlignment.o

# target to build an object file
src/CodonSequenceAlignment.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/CodonSequenceAlignment.cpp.o
.PHONY : src/CodonSequenceAlignment.cpp.o

src/CodonSequenceAlignment.i: src/CodonSequenceAlignment.cpp.i

.PHONY : src/CodonSequenceAlignment.i

# target to preprocess a source file
src/CodonSequenceAlignment.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/CodonSequenceAlignment.cpp.i
.PHONY : src/CodonSequenceAlignment.cpp.i

src/CodonSequenceAlignment.s: src/CodonSequenceAlignment.cpp.s

.PHONY : src/CodonSequenceAlignment.s

# target to generate assembly for a file
src/CodonSequenceAlignment.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/CodonSequenceAlignment.cpp.s
.PHONY : src/CodonSequenceAlignment.cpp.s

src/CodonStateSpace.o: src/CodonStateSpace.cpp.o

.PHONY : src/CodonStateSpace.o

# target to build an object file
src/CodonStateSpace.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/CodonStateSpace.cpp.o
.PHONY : src/CodonStateSpace.cpp.o

src/CodonStateSpace.i: src/CodonStateSpace.cpp.i

.PHONY : src/CodonStateSpace.i

# target to preprocess a source file
src/CodonStateSpace.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/CodonStateSpace.cpp.i
.PHONY : src/CodonStateSpace.cpp.i

src/CodonStateSpace.s: src/CodonStateSpace.cpp.s

.PHONY : src/CodonStateSpace.s

# target to generate assembly for a file
src/CodonStateSpace.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/CodonStateSpace.cpp.s
.PHONY : src/CodonStateSpace.cpp.s

src/CodonSubMatrix.o: src/CodonSubMatrix.cpp.o

.PHONY : src/CodonSubMatrix.o

# target to build an object file
src/CodonSubMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/CodonSubMatrix.cpp.o
.PHONY : src/CodonSubMatrix.cpp.o

src/CodonSubMatrix.i: src/CodonSubMatrix.cpp.i

.PHONY : src/CodonSubMatrix.i

# target to preprocess a source file
src/CodonSubMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/CodonSubMatrix.cpp.i
.PHONY : src/CodonSubMatrix.cpp.i

src/CodonSubMatrix.s: src/CodonSubMatrix.cpp.s

.PHONY : src/CodonSubMatrix.s

# target to generate assembly for a file
src/CodonSubMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/CodonSubMatrix.cpp.s
.PHONY : src/CodonSubMatrix.cpp.s

src/DiffSel.o: src/DiffSel.cpp.o

.PHONY : src/DiffSel.o

# target to build an object file
src/DiffSel.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel.dir/build.make CMakeFiles/diffsel.dir/src/DiffSel.cpp.o
.PHONY : src/DiffSel.cpp.o

src/DiffSel.i: src/DiffSel.cpp.i

.PHONY : src/DiffSel.i

# target to preprocess a source file
src/DiffSel.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel.dir/build.make CMakeFiles/diffsel.dir/src/DiffSel.cpp.i
.PHONY : src/DiffSel.cpp.i

src/DiffSel.s: src/DiffSel.cpp.s

.PHONY : src/DiffSel.s

# target to generate assembly for a file
src/DiffSel.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel.dir/build.make CMakeFiles/diffsel.dir/src/DiffSel.cpp.s
.PHONY : src/DiffSel.cpp.s

src/DiffSelSparse.o: src/DiffSelSparse.cpp.o

.PHONY : src/DiffSelSparse.o

# target to build an object file
src/DiffSelSparse.cpp.o:
	$(MAKE) -f CMakeFiles/diffselsparse.dir/build.make CMakeFiles/diffselsparse.dir/src/DiffSelSparse.cpp.o
.PHONY : src/DiffSelSparse.cpp.o

src/DiffSelSparse.i: src/DiffSelSparse.cpp.i

.PHONY : src/DiffSelSparse.i

# target to preprocess a source file
src/DiffSelSparse.cpp.i:
	$(MAKE) -f CMakeFiles/diffselsparse.dir/build.make CMakeFiles/diffselsparse.dir/src/DiffSelSparse.cpp.i
.PHONY : src/DiffSelSparse.cpp.i

src/DiffSelSparse.s: src/DiffSelSparse.cpp.s

.PHONY : src/DiffSelSparse.s

# target to generate assembly for a file
src/DiffSelSparse.cpp.s:
	$(MAKE) -f CMakeFiles/diffselsparse.dir/build.make CMakeFiles/diffselsparse.dir/src/DiffSelSparse.cpp.s
.PHONY : src/DiffSelSparse.cpp.s

src/GTRSubMatrix.o: src/GTRSubMatrix.cpp.o

.PHONY : src/GTRSubMatrix.o

# target to build an object file
src/GTRSubMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/GTRSubMatrix.cpp.o
.PHONY : src/GTRSubMatrix.cpp.o

src/GTRSubMatrix.i: src/GTRSubMatrix.cpp.i

.PHONY : src/GTRSubMatrix.i

# target to preprocess a source file
src/GTRSubMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/GTRSubMatrix.cpp.i
.PHONY : src/GTRSubMatrix.cpp.i

src/GTRSubMatrix.s: src/GTRSubMatrix.cpp.s

.PHONY : src/GTRSubMatrix.s

# target to generate assembly for a file
src/GTRSubMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/GTRSubMatrix.cpp.s
.PHONY : src/GTRSubMatrix.cpp.s

src/MSCodonSubMatrix.o: src/MSCodonSubMatrix.cpp.o

.PHONY : src/MSCodonSubMatrix.o

# target to build an object file
src/MSCodonSubMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/MSCodonSubMatrix.cpp.o
.PHONY : src/MSCodonSubMatrix.cpp.o

src/MSCodonSubMatrix.i: src/MSCodonSubMatrix.cpp.i

.PHONY : src/MSCodonSubMatrix.i

# target to preprocess a source file
src/MSCodonSubMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/MSCodonSubMatrix.cpp.i
.PHONY : src/MSCodonSubMatrix.cpp.i

src/MSCodonSubMatrix.s: src/MSCodonSubMatrix.cpp.s

.PHONY : src/MSCodonSubMatrix.s

# target to generate assembly for a file
src/MSCodonSubMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/MSCodonSubMatrix.cpp.s
.PHONY : src/MSCodonSubMatrix.cpp.s

src/MultiGeneSingleOmega.o: src/MultiGeneSingleOmega.cpp.o

.PHONY : src/MultiGeneSingleOmega.o

# target to build an object file
src/MultiGeneSingleOmega.cpp.o:
	$(MAKE) -f CMakeFiles/multigenesingleomega.dir/build.make CMakeFiles/multigenesingleomega.dir/src/MultiGeneSingleOmega.cpp.o
.PHONY : src/MultiGeneSingleOmega.cpp.o

src/MultiGeneSingleOmega.i: src/MultiGeneSingleOmega.cpp.i

.PHONY : src/MultiGeneSingleOmega.i

# target to preprocess a source file
src/MultiGeneSingleOmega.cpp.i:
	$(MAKE) -f CMakeFiles/multigenesingleomega.dir/build.make CMakeFiles/multigenesingleomega.dir/src/MultiGeneSingleOmega.cpp.i
.PHONY : src/MultiGeneSingleOmega.cpp.i

src/MultiGeneSingleOmega.s: src/MultiGeneSingleOmega.cpp.s

.PHONY : src/MultiGeneSingleOmega.s

# target to generate assembly for a file
src/MultiGeneSingleOmega.cpp.s:
	$(MAKE) -f CMakeFiles/multigenesingleomega.dir/build.make CMakeFiles/multigenesingleomega.dir/src/MultiGeneSingleOmega.cpp.s
.PHONY : src/MultiGeneSingleOmega.cpp.s

src/PhyloProcess.o: src/PhyloProcess.cpp.o

.PHONY : src/PhyloProcess.o

# target to build an object file
src/PhyloProcess.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/PhyloProcess.cpp.o
.PHONY : src/PhyloProcess.cpp.o

src/PhyloProcess.i: src/PhyloProcess.cpp.i

.PHONY : src/PhyloProcess.i

# target to preprocess a source file
src/PhyloProcess.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/PhyloProcess.cpp.i
.PHONY : src/PhyloProcess.cpp.i

src/PhyloProcess.s: src/PhyloProcess.cpp.s

.PHONY : src/PhyloProcess.s

# target to generate assembly for a file
src/PhyloProcess.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/PhyloProcess.cpp.s
.PHONY : src/PhyloProcess.cpp.s

src/Random.o: src/Random.cpp.o

.PHONY : src/Random.o

# target to build an object file
src/Random.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Random.cpp.o
.PHONY : src/Random.cpp.o

src/Random.i: src/Random.cpp.i

.PHONY : src/Random.i

# target to preprocess a source file
src/Random.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Random.cpp.i
.PHONY : src/Random.cpp.i

src/Random.s: src/Random.cpp.s

.PHONY : src/Random.s

# target to generate assembly for a file
src/Random.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Random.cpp.s
.PHONY : src/Random.cpp.s

src/ReadDiffSel.o: src/ReadDiffSel.cpp.o

.PHONY : src/ReadDiffSel.o

# target to build an object file
src/ReadDiffSel.cpp.o:
	$(MAKE) -f CMakeFiles/readdiffsel.dir/build.make CMakeFiles/readdiffsel.dir/src/ReadDiffSel.cpp.o
.PHONY : src/ReadDiffSel.cpp.o

src/ReadDiffSel.i: src/ReadDiffSel.cpp.i

.PHONY : src/ReadDiffSel.i

# target to preprocess a source file
src/ReadDiffSel.cpp.i:
	$(MAKE) -f CMakeFiles/readdiffsel.dir/build.make CMakeFiles/readdiffsel.dir/src/ReadDiffSel.cpp.i
.PHONY : src/ReadDiffSel.cpp.i

src/ReadDiffSel.s: src/ReadDiffSel.cpp.s

.PHONY : src/ReadDiffSel.s

# target to generate assembly for a file
src/ReadDiffSel.cpp.s:
	$(MAKE) -f CMakeFiles/readdiffsel.dir/build.make CMakeFiles/readdiffsel.dir/src/ReadDiffSel.cpp.s
.PHONY : src/ReadDiffSel.cpp.s

src/Sample.o: src/Sample.cpp.o

.PHONY : src/Sample.o

# target to build an object file
src/Sample.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Sample.cpp.o
.PHONY : src/Sample.cpp.o

src/Sample.i: src/Sample.cpp.i

.PHONY : src/Sample.i

# target to preprocess a source file
src/Sample.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Sample.cpp.i
.PHONY : src/Sample.cpp.i

src/Sample.s: src/Sample.cpp.s

.PHONY : src/Sample.s

# target to generate assembly for a file
src/Sample.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Sample.cpp.s
.PHONY : src/Sample.cpp.s

src/SequenceAlignment.o: src/SequenceAlignment.cpp.o

.PHONY : src/SequenceAlignment.o

# target to build an object file
src/SequenceAlignment.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/SequenceAlignment.cpp.o
.PHONY : src/SequenceAlignment.cpp.o

src/SequenceAlignment.i: src/SequenceAlignment.cpp.i

.PHONY : src/SequenceAlignment.i

# target to preprocess a source file
src/SequenceAlignment.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/SequenceAlignment.cpp.i
.PHONY : src/SequenceAlignment.cpp.i

src/SequenceAlignment.s: src/SequenceAlignment.cpp.s

.PHONY : src/SequenceAlignment.s

# target to generate assembly for a file
src/SequenceAlignment.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/SequenceAlignment.cpp.s
.PHONY : src/SequenceAlignment.cpp.s

src/SingleOmega.o: src/SingleOmega.cpp.o

.PHONY : src/SingleOmega.o

# target to build an object file
src/SingleOmega.cpp.o:
	$(MAKE) -f CMakeFiles/singleomega.dir/build.make CMakeFiles/singleomega.dir/src/SingleOmega.cpp.o
.PHONY : src/SingleOmega.cpp.o

src/SingleOmega.i: src/SingleOmega.cpp.i

.PHONY : src/SingleOmega.i

# target to preprocess a source file
src/SingleOmega.cpp.i:
	$(MAKE) -f CMakeFiles/singleomega.dir/build.make CMakeFiles/singleomega.dir/src/SingleOmega.cpp.i
.PHONY : src/SingleOmega.cpp.i

src/SingleOmega.s: src/SingleOmega.cpp.s

.PHONY : src/SingleOmega.s

# target to generate assembly for a file
src/SingleOmega.cpp.s:
	$(MAKE) -f CMakeFiles/singleomega.dir/build.make CMakeFiles/singleomega.dir/src/SingleOmega.cpp.s
.PHONY : src/SingleOmega.cpp.s

src/SubMatrix.o: src/SubMatrix.cpp.o

.PHONY : src/SubMatrix.o

# target to build an object file
src/SubMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/SubMatrix.cpp.o
.PHONY : src/SubMatrix.cpp.o

src/SubMatrix.i: src/SubMatrix.cpp.i

.PHONY : src/SubMatrix.i

# target to preprocess a source file
src/SubMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/SubMatrix.cpp.i
.PHONY : src/SubMatrix.cpp.i

src/SubMatrix.s: src/SubMatrix.cpp.s

.PHONY : src/SubMatrix.s

# target to generate assembly for a file
src/SubMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/SubMatrix.cpp.s
.PHONY : src/SubMatrix.cpp.s

src/Tree.o: src/Tree.cpp.o

.PHONY : src/Tree.o

# target to build an object file
src/Tree.cpp.o:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Tree.cpp.o
.PHONY : src/Tree.cpp.o

src/Tree.i: src/Tree.cpp.i

.PHONY : src/Tree.i

# target to preprocess a source file
src/Tree.cpp.i:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Tree.cpp.i
.PHONY : src/Tree.cpp.i

src/Tree.s: src/Tree.cpp.s

.PHONY : src/Tree.s

# target to generate assembly for a file
src/Tree.cpp.s:
	$(MAKE) -f CMakeFiles/diffsel_lib.dir/build.make CMakeFiles/diffsel_lib.dir/src/Tree.cpp.s
.PHONY : src/Tree.cpp.s

src/test.o: src/test.cpp.o

.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i

.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s

.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

utils/Correlation.o: utils/Correlation.cpp.o

.PHONY : utils/Correlation.o

# target to build an object file
utils/Correlation.cpp.o:
	$(MAKE) -f CMakeFiles/tracecomp.dir/build.make CMakeFiles/tracecomp.dir/utils/Correlation.cpp.o
.PHONY : utils/Correlation.cpp.o

utils/Correlation.i: utils/Correlation.cpp.i

.PHONY : utils/Correlation.i

# target to preprocess a source file
utils/Correlation.cpp.i:
	$(MAKE) -f CMakeFiles/tracecomp.dir/build.make CMakeFiles/tracecomp.dir/utils/Correlation.cpp.i
.PHONY : utils/Correlation.cpp.i

utils/Correlation.s: utils/Correlation.cpp.s

.PHONY : utils/Correlation.s

# target to generate assembly for a file
utils/Correlation.cpp.s:
	$(MAKE) -f CMakeFiles/tracecomp.dir/build.make CMakeFiles/tracecomp.dir/utils/Correlation.cpp.s
.PHONY : utils/Correlation.cpp.s

utils/TraceComp.o: utils/TraceComp.cpp.o

.PHONY : utils/TraceComp.o

# target to build an object file
utils/TraceComp.cpp.o:
	$(MAKE) -f CMakeFiles/tracecomp.dir/build.make CMakeFiles/tracecomp.dir/utils/TraceComp.cpp.o
.PHONY : utils/TraceComp.cpp.o

utils/TraceComp.i: utils/TraceComp.cpp.i

.PHONY : utils/TraceComp.i

# target to preprocess a source file
utils/TraceComp.cpp.i:
	$(MAKE) -f CMakeFiles/tracecomp.dir/build.make CMakeFiles/tracecomp.dir/utils/TraceComp.cpp.i
.PHONY : utils/TraceComp.cpp.i

utils/TraceComp.s: utils/TraceComp.cpp.s

.PHONY : utils/TraceComp.s

# target to generate assembly for a file
utils/TraceComp.cpp.s:
	$(MAKE) -f CMakeFiles/tracecomp.dir/build.make CMakeFiles/tracecomp.dir/utils/TraceComp.cpp.s
.PHONY : utils/TraceComp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tests"
	@echo "... diffsel_lib"
	@echo "... multigenesingleomega"
	@echo "... diffselsparse"
	@echo "... readdiffsel"
	@echo "... tracecomp"
	@echo "... singleomega"
	@echo "... diffsel"
	@echo "... src/BiologicalSequences.o"
	@echo "... src/BiologicalSequences.i"
	@echo "... src/BiologicalSequences.s"
	@echo "... src/BranchSitePath.o"
	@echo "... src/BranchSitePath.i"
	@echo "... src/BranchSitePath.s"
	@echo "... src/Chain.o"
	@echo "... src/Chain.i"
	@echo "... src/Chain.s"
	@echo "... src/Chrono.o"
	@echo "... src/Chrono.i"
	@echo "... src/Chrono.s"
	@echo "... src/CodonSequenceAlignment.o"
	@echo "... src/CodonSequenceAlignment.i"
	@echo "... src/CodonSequenceAlignment.s"
	@echo "... src/CodonStateSpace.o"
	@echo "... src/CodonStateSpace.i"
	@echo "... src/CodonStateSpace.s"
	@echo "... src/CodonSubMatrix.o"
	@echo "... src/CodonSubMatrix.i"
	@echo "... src/CodonSubMatrix.s"
	@echo "... src/DiffSel.o"
	@echo "... src/DiffSel.i"
	@echo "... src/DiffSel.s"
	@echo "... src/DiffSelSparse.o"
	@echo "... src/DiffSelSparse.i"
	@echo "... src/DiffSelSparse.s"
	@echo "... src/GTRSubMatrix.o"
	@echo "... src/GTRSubMatrix.i"
	@echo "... src/GTRSubMatrix.s"
	@echo "... src/MSCodonSubMatrix.o"
	@echo "... src/MSCodonSubMatrix.i"
	@echo "... src/MSCodonSubMatrix.s"
	@echo "... src/MultiGeneSingleOmega.o"
	@echo "... src/MultiGeneSingleOmega.i"
	@echo "... src/MultiGeneSingleOmega.s"
	@echo "... src/PhyloProcess.o"
	@echo "... src/PhyloProcess.i"
	@echo "... src/PhyloProcess.s"
	@echo "... src/Random.o"
	@echo "... src/Random.i"
	@echo "... src/Random.s"
	@echo "... src/ReadDiffSel.o"
	@echo "... src/ReadDiffSel.i"
	@echo "... src/ReadDiffSel.s"
	@echo "... src/Sample.o"
	@echo "... src/Sample.i"
	@echo "... src/Sample.s"
	@echo "... src/SequenceAlignment.o"
	@echo "... src/SequenceAlignment.i"
	@echo "... src/SequenceAlignment.s"
	@echo "... src/SingleOmega.o"
	@echo "... src/SingleOmega.i"
	@echo "... src/SingleOmega.s"
	@echo "... src/SubMatrix.o"
	@echo "... src/SubMatrix.i"
	@echo "... src/SubMatrix.s"
	@echo "... src/Tree.o"
	@echo "... src/Tree.i"
	@echo "... src/Tree.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... utils/Correlation.o"
	@echo "... utils/Correlation.i"
	@echo "... utils/Correlation.s"
	@echo "... utils/TraceComp.o"
	@echo "... utils/TraceComp.i"
	@echo "... utils/TraceComp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

